services:
  webapp:
    build: .   
    volumes:
      - .:/app         # build from the Dockerfile in this folder
    ports:
      - "5000:5000"     # map localhost:5000 to the container's port 5000
